# Generated by Django 3.2.7 on 2021-09-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='user_name')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='user_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_works', models.IntegerField()),
                ('duration', models.TimeField()),
                ('client_name', models.CharField(max_length=100)),
                ('describtion', models.CharField(max_length=600)),
            ],
        ),
    ]
