# Generated by Django 3.2.7 on 2021-09-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cincinatty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('client_name', models.CharField(max_length=100)),
                ('describtion', models.CharField(max_length=600)),
            ],
        ),
    ]
